# version: '3.9'

# services:
#   api:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis
#       - mysql
#     restart: on-failure
#     volumes:
#       - .:/app
#   web:
#     build: ./frontend
#     # command: npm run serve
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/frontend
#   mysql:
#     image: mysql:8.0
#     ports:
#       - "3306:3306"
#     restart: always
#     environment:
#       - MYSQL_DATABASE=uweflixDB
#       - MYSQL_ROOT_PASSWORD=password
#     volumes:
#       - mysql-data:/var/lib/mysql
#   redis:
#     image: redis:6.2-alpine
#     ports:
#       - "6379:6379"
#     restart: always
#     volumes:
#       - redis-data:/data
#   smtp4dev:
#     image: rnwood/smtp4dev:v3
#     ports:
#       - "5000:80"
#       - 25:25
#     restart: always
#   celery: 
#     build: .
#     command: celery -A cinema worker --loglevel=info
#     depends_on:
#       - redis
#     volumes: 
#       - .:/app
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - CELERY_RESULT_BACKEND=redis://redis:6379/0
#   celery-beat:
#     build: .
#     command: celery -A cinema beat --loglevel=info
#     depends_on:
#       - redis
#     volumes: 
#       - .:/app
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - CELERY_RESULT_BACKEND=redis://redis:6379/0
#   flower:
#     build: .
#     command: celery -A cinema flower
#     depends_on:
#       - redis
#       - celery
#     environment:
#       - DEBUG=true
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - CELERY_RESULT_BACKEND=redis://redis:6379/0
#     ports:
#       - 5555:5555

# volumes:
#   mysql-data: 
#   redis-data: 


version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    restart: on-failure
    volumes:
      - .:/app
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=uweflixDB
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - "5000:80"
      - 25:25
    restart: always
  celery: 
    build: .
    command: celery -A cinema worker --loglevel=info
    depends_on:
      - redis
    volumes: 
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  celery-beat:
    build: .
    command: celery -A cinema beat --loglevel=info
    depends_on:
      - redis
    volumes: 
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  flower:
    build: .
    command: celery -A cinema flower
    depends_on:
      - redis
      - celery
    environment:
      - DEBUG=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 5555:5555

volumes:
  mysql-data: 
  redis-data: 
