# Generated by Django 4.1.6 on 2023-03-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0002_remove_address_street_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('age_rating', models.SmallIntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('short_trailer_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=255)),
                ('capacity', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing_time', models.DateTimeField()),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.film')),
                ('screen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.screen')),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='address',
        ),
        migrations.RemoveField(
            model_name='club',
            name='contact_details',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
