# Generated by Django 4.1.6 on 2023-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0002_filmimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmimage',
            name='image',
            field=models.ImageField(default=1, upload_to='cinema/images'),
            preserve_default=False,
        ),
    ]
