# Generated by Django 4.1.6 on 2023-03-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0004_showing_tickets_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('S', 'Student'), ('A', 'Adult'), ('C', 'Child')], default='S', max_length=1)),
                ('ticket_price', models.CharField(choices=[('S', '10'), ('A', '15'), ('C', '5')], max_length=1)),
                ('showing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.showing')),
            ],
        ),
    ]
