# Generated by Django 4.1.6 on 2023-03-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0005_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
