# Generated by Django 4.1.6 on 2023-05-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0005_price_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price_type',
        ),
    ]
