# Generated by Django 4.1.6 on 2023-05-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0005_cinemamanager_expiration_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemamanager',
            old_name='expiration_data',
            new_name='expiration_date',
        ),
    ]
