# Generated by Django 4.1.6 on 2023-03-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0006_alter_film_title_alter_screen_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showing', to='UWEFlix.film'),
        ),
    ]
