# Generated by Django 4.1.6 on 2023-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0008_alter_showing_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=32, null=True)),
                ('film', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
