# Generated by Django 4.1.6 on 2023-05-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0008_remove_film_image_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
