# Generated by Django 4.1.6 on 2023-05-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0009_film_is_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
