# Generated by Django 4.1.6 on 2023-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0009_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='film',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='screen',
        ),
    ]
