# Generated by Django 4.1.6 on 2023-03-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0010_alter_cinemamanager_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemamanager',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AddField(
            model_name='film',
            name='image_uri',
            field=models.CharField(default='fightclub.jpg', max_length=255),
        ),
    ]
