# Generated by Django 4.1.6 on 2023-05-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0010_rename_is_activate_film_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
