# Generated by Django 4.1.6 on 2023-03-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0010_alter_cinemamanager_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemamanager',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
