# Generated by Django 4.1.6 on 2023-03-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0010_alter_cinemamanager_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemamanager',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AddField(
            model_name='showing',
            name='showing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='showing_time',
            field=models.TimeField(),
        ),
    ]
