# Generated by Django 4.1.6 on 2023-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0011_booking_customer_booking_film_booking_screen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
