# Generated by Django 4.1.6 on 2023-03-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0011_alter_cinemamanager_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='film',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
