# Generated by Django 4.1.6 on 2023-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0011_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
