# Generated by Django 4.1.6 on 2023-03-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0012_ticket_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='screen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
