# Generated by Django 4.1.6 on 2023-03-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0012_booking_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
