# Generated by Django 4.1.6 on 2023-03-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0013_booking_booking_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='showing_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='UWEFlix.film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.DurationField(),
        ),
    ]
