# Generated by Django 4.1.6 on 2023-03-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0013_ticket_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='showing_time',
            field=models.DateField(null=True),
        ),
    ]
