# Generated by Django 4.1.6 on 2023-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0014_remove_booking_showing_time_alter_booking_film_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='screen',
        ),
    ]
