# Generated by Django 4.1.6 on 2023-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0015_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='film',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='screen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='showing_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_amount',
            field=models.IntegerField(default=0),
        ),
    ]
