# Generated by Django 4.1.6 on 2023-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0015_remove_booking_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='screen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='showing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
