# Generated by Django 4.1.6 on 2023-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0016_booking_film_booking_screen_booking_showing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
