# Generated by Django 4.1.6 on 2023-03-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0016_bookingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='showing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='UWEFlix.showing'),
        ),
    ]
