# Generated by Django 4.1.6 on 2023-03-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0017_alter_ticket_showing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UWEFlix.ticket'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookingitem',
            unique_together={('booking', 'ticket')},
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='showing',
        ),
    ]
