# Generated by Django 4.1.6 on 2023-03-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0017_alter_film_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='showing_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
