# Generated by Django 4.1.6 on 2023-03-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0018_alter_bookingitem_unique_together_bookingitem_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screen', to='UWEFlix.screen'),
        ),
    ]
