# Generated by Django 4.1.6 on 2023-03-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0019_alter_showing_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showing', to='UWEFlix.screen'),
        ),
    ]
