# Generated by Django 4.1.6 on 2023-03-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0019_alter_ticket_showing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='showing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
