# Generated by Django 4.1.6 on 2023-03-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0020_alter_ticket_showing_alter_ticket_ticket_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ticket_amount',
            new_name='adult',
        ),
        migrations.AddField(
            model_name='booking',
            name='child',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='showing_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_showing_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
