# Generated by Django 4.1.6 on 2023-03-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0020_alter_showing_screen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_price',
        ),
    ]
