# Generated by Django 4.1.6 on 2023-03-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0021_rename_ticket_amount_booking_adult_booking_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='showing',
        ),
    ]
