# Generated by Django 4.1.6 on 2023-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0021_remove_ticket_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=5),
        ),
        migrations.AddField(
            model_name='showing',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
        migrations.AddField(
            model_name='showing',
            name='student_price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
