# Generated by Django 4.1.6 on 2023-03-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0022_showing_adult_price_showing_child_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='showing',
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='showing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_item', to='UWEFlix.showing'),
            preserve_default=False,
        ),
    ]
