# Generated by Django 4.1.6 on 2023-03-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0023_remove_ticket_showing_bookingitem_showing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
