# Generated by Django 4.1.6 on 2023-03-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0024_ticket_ticket_booking_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_ref',
        ),
    ]
