# Generated by Django 4.1.6 on 2023-03-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0025_remove_booking_booking_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
