# Generated by Django 4.1.6 on 2023-03-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0025_rename_price_bookingitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='total_price',
        ),
    ]
