# Generated by Django 4.1.6 on 2023-03-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0028_alter_bookingitem_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingitem',
            unique_together={('booking', 'ticket_type', 'showing')},
        ),
    ]
