# Generated by Django 4.1.6 on 2023-03-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0029_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
