# Generated by Django 4.1.6 on 2023-03-20 13:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0030_alter_bookingitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cardholder_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='card_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='UWEFlix.carddetails'),
            preserve_default=False,
        ),
    ]
