# Generated by Django 4.1.6 on 2023-03-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0011_alter_cinemamanager_options_film_image_uri'),
        ('UWEFlix', '0030_alter_bookingitem_unique_together'),
    ]

    operations = [
    ]
