# Generated by Django 4.1.6 on 2023-03-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0031_carddetails_remove_customer_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='UWEFlix.carddetails'),
        ),
    ]
