# Generated by Django 4.1.6 on 2023-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0032_remove_ticket_ticket_showing_ref_ticket_showing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='showing',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_showing_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
