# Generated by Django 4.1.6 on 2023-03-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0033_remove_ticket_showing_ticket_ticket_showing_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_showing_ref',
        ),
        migrations.AddField(
            model_name='ticket',
            name='showing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.showing'),
        ),
    ]
