# Generated by Django 4.1.6 on 2023-03-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0034_remove_ticket_ticket_showing_ref_ticket_showing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='showing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.showing'),
        ),
    ]
