# Generated by Django 4.1.6 on 2023-03-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0032_alter_bookingitem_quantity'),
        ('UWEFlix', '0034_order_orderitem'),
    ]

    operations = [
    ]
