# Generated by Django 4.1.6 on 2023-03-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0035_merge_20230323_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('student', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('adult', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.RemoveField(
            model_name='showing',
            name='adult_price',
        ),
        migrations.RemoveField(
            model_name='showing',
            name='child_price',
        ),
        migrations.RemoveField(
            model_name='showing',
            name='student_price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='UWEFlix.order'),
        ),
        migrations.AddField(
            model_name='showing',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='showing', to='UWEFlix.price'),
            preserve_default=False,
        ),
    ]
