# Generated by Django 4.1.6 on 2023-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0035_alter_ticket_showing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adult',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='showing',
            name='tickets_sold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
