# Generated by Django 4.1.6 on 2023-03-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=50)),
                ('landline_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.address')),
                ('contact_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.contactdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='club.club')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.paymentdetails')),
            ],
        ),
    ]
