# Generated by Django 4.1.6 on 2023-03-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmanager',
            name='date',
        ),
    ]
