# Generated by Django 4.1.6 on 2023-03-13 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.paymentdetails'),
        ),
    ]
