# Generated by Django 4.1.6 on 2023-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
