# Generated by Django 4.1.6 on 2023-04-13 23:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('club', '0002_bookingitem_showing_id_bookingitem_showing_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubBookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(default='S', max_length=1)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('showing_id', models.PositiveIntegerField(blank=True, null=True)),
                ('club_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_items', to='club.clubbooking')),
                ('showing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ClubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_order', to='club.account')),
            ],
        ),
        migrations.CreateModel(
            name='ClubOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ticket_type', models.CharField(default='S', max_length=1)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('club_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_items', to='club.cluborder')),
                ('showing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='showing_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='showing_type',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
