# Generated by Django 4.1.6 on 2023-03-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_account_discount_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymmentDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='account',
            name='payment_details',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.paymmentdetials'),
            preserve_default=False,
        ),
    ]
