# Generated by Django 4.1.6 on 2023-03-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_accountmanager_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_number',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
