# Generated by Django 4.1.6 on 2023-03-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_paymmentdetials_remove_account_card_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymmentDetials',
            new_name='PaymmentDetails',
        ),
    ]
