# Generated by Django 4.1.6 on 2023-03-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubrepresentative_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrepresentative',
            name='club_representative_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubrepresentative',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubrepresentative',
            name='password',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
