# Generated by Django 4.1.6 on 2023-03-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_clubrepresentative_club_representative_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrepresentative',
            name='password',
        ),
        migrations.AlterField(
            model_name='clubrepresentative',
            name='club_representative_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
