# Generated by Django 4.1.6 on 2023-05-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_rename_payment_status_discountrequest_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluborder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
