# Generated by Django 4.1.6 on 2023-03-15 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0005_remove_clubrepresentative_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postcode',
            new_name='post_code',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='club_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='clubrepresentative',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubrepresentative',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubrepresentative',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='club_email',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='club.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_details',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='club.contactdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubrepresentative',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='landline_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='mobile_number',
            field=models.CharField(max_length=255),
        ),
    ]
