# Generated by Django 4.1.6 on 2023-03-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_rename_postcode_address_post_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='club', to='club.address'),
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='club', to='club.contactdetails'),
        ),
    ]
