# Generated by Django 4.1.6 on 2023-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_cluborder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluborder',
            name='cancellation_request',
            field=models.BooleanField(default=False),
        ),
    ]
