# Generated by Django 4.1.6 on 2023-04-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_booking_order_orderitem_bookingitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingitem',
            unique_together=set(),
        ),
    ]
