# Generated by Django 4.1.6 on 2023-05-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_cluborder_cancellation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluborder',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClubOrderCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('placed_at', models.DateField(auto_now_add=True)),
                ('club_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='club.cluborder')),
            ],
        ),
    ]
