# Generated by Django 4.1.6 on 2023-03-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_clubrepresentative_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrepresentative',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clubrepresentative',
            name='last_name',
        ),
    ]
