# Generated by Django 4.1.6 on 2023-04-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_bookingitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='object_id',
            new_name='showing_id',
        ),
        migrations.RenameField(
            model_name='bookingitem',
            old_name='content_type',
            new_name='showing_type',
        ),
    ]
