# Generated by Django 4.1.6 on 2023-05-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_cluborder_total_paid_clubordercancellationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubordercancellationrequest',
            name='club_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_cancellation', to='club.cluborder'),
        ),
    ]
