# Generated by Django 4.1.6 on 2023-03-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_remove_clubrepresentative_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrepresentative',
            name='club_representative_number',
        ),
        migrations.RemoveField(
            model_name='clubrepresentative',
            name='name',
        ),
    ]
