# Generated by Django 4.1.6 on 2023-04-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_alter_bookingitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='object_id',
            new_name='showing_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='content_type',
            new_name='showing_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='club',
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.account'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ticket_type',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
