# Generated by Django 4.1.6 on 2023-03-16 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_remove_clubrepresentative_club_representative_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrepresentative',
            name='club',
            field=models.OneToOneField(default=324535476, on_delete=django.db.models.deletion.PROTECT, related_name='club_representative', to='club.club'),
            preserve_default=False,
        ),
    ]
