# Generated by Django 4.1.6 on 2023-04-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_rename_object_id_orderitem_showing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='club.account'),
        ),
    ]
