# Generated by Django 4.1.6 on 2023-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
