# Generated by Django 4.1.6 on 2023-04-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_account_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='statements',
            name='amount_due',
        ),
        migrations.AddField(
            model_name='statements',
            name='name',
            field=models.CharField(default='end of month statement: April-2023', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='club.creditlist'),
        ),
    ]
