# Generated by Django 4.1.6 on 2023-04-12 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_remove_account_credit_list_creditlist_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditlist',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='credit_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='club.creditlist'),
        ),
    ]
