# Generated by Django 4.1.6 on 2023-04-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_remove_creditlist_account_account_credit_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='credit_list',
        ),
        migrations.RemoveField(
            model_name='creditlist',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='creditlist',
            name='placed_at',
        ),
        migrations.AddField(
            model_name='creditlist',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_list', to='club.account'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Statements',
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='club.creditlist'),
        ),
    ]
