# Generated by Django 4.1.6 on 2023-04-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0018_credit_remove_account_credit_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='club.creditlist'),
        ),
    ]
