# Generated by Django 4.1.6 on 2023-04-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0019_alter_credit_credit_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='credit_list',
        ),
        migrations.AddField(
            model_name='account',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='club.credit'),
        ),
        migrations.DeleteModel(
            name='CreditList',
        ),
    ]
