# Generated by Django 4.1.6 on 2023-04-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_remove_credit_credit_list_account_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='placed_at',
        ),
        migrations.AddField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='club.account'),
        ),
        migrations.AddField(
            model_name='credit',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='club.credititem'),
        ),
    ]
