# Generated by Django 4.1.6 on 2023-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0021_credititem_remove_account_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='items',
        ),
        migrations.AddField(
            model_name='credit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='CreditItem',
        ),
    ]
